#include <iostream>
using namespace std;
main()
{
    int array[5];
    array[4] = 12;
    array[3] = 233;
    array[2] = 334;
    array[1] = 33;
    array[0] = 333;
    cout << "first element of array : " << array[0] << endl;
    cout << "second element of array : " << array[1] << endl;
    cout << "third element of array : " << array[2] << endl;
    cout << "fourth element of array : " << array[3] << endl;
    cout << "fifth element of array : " << array[4] << endl;
}
